name: ad
channels:
- defaults
dependencies:
- python=3.6
- h5py
- matplotlib
- networkx
- numpy
- pandas
- pip
- scikit-learn
- scipy
- seaborn
- openpyxl
- lxml
- xlrd
- joblib
- pip:
  - keras
  - tensorflow
  - tqdm
  - untangle
  - hmmlearn
  - untangle
  - tqdm
  - pushbullet.py